Repository algolia/algolia-react-boilerplate, pull requests merged in 2022-08, with the labels that each got.

#300 Carousel Draggable
  src/Main.jsx
  src/components/carousels/HomeCarousel.jsx
  src/components/carousels/SCSS/carousels.scss
  src/pages/homepage/HomePage.jsx
  src/pages/searchResultPage/SearchResultsPage.jsx
Labels: Bug, M

#262 Feat translation improvement
  README.md
  package.json
  src/Index.jsx
  src/components/carousels/HomeCarousel.jsx
  src/components/federatedSearch/FederatedSearch.jsx
  src/components/federatedSearch/components/BlogPost.jsx
  src/components/federatedSearch/components/Category.jsx
  src/components/federatedSearch/components/Products.jsx
  src/components/federatedSearch/components/QuerySuggestions.jsx
  src/components/federatedSearch/components/RecentSearches.jsx
  src/components/hits/components/injected-hits/connectInjectedHits.jsx
  src/components/hits/components/injected-hits/index.jsx
  src/components/recommend/trending/TrendingFacetValues.jsx
  src/components/recommend/trending/TrendingProducts.jsx
  src/components/searchbox/SCSS/searchbox.scss
  src/components/searchbox/SearchBox.jsx
  src/components/searchbox/components/SearchInCategory.jsx
  src/components/selector/Selectors.jsx
  src/components/stats/Stats.jsx
  src/config/carouselConfig.js
  src/config/featuresConfig.js
  src/config/languagesConfig.js
  src/config/searchboxConfig.js
  src/config/translation.js
  src/config/trendingConfig.js
  src/pages/homepage/HomePage.jsx
  src/pages/productDetailsPage/ProductDetails.jsx
  src/pages/productDetailsPage/SCSS/productDetails.scss
Labels: Improvement

#343 added back show more css in facets SRP
  src/components/facets/SCSS/facets.scss
Labels: Bug
