Repository algolia/algolia-react-boilerplate, pull requests merged in 2022-07, with the labels that each got.

#264 Refactor resize listener
  src/App.jsx
  src/Main.jsx
  src/components/carousels/HomeCarousel.jsx
  src/components/demoGuide/DemoGuide.jsx
  src/components/federatedSearch/FederatedSearch.jsx
  src/components/header/Header.jsx
  src/components/hits/HitsSkeletonLoader.jsx
  src/components/hits/components/HitsSkeletonLoader.jsx
  src/hooks/useScreenSize.jsx
  src/pages/productDetailsPage/ProductDetails.jsx
  src/utils/ScreenResizer.jsx
Labels: Improvement, S

#267 stylesheet import for skeleton
  src/scss/index.scss
Labels: S

#275 Handling API Errors
  README.md
  src/Main.jsx
  src/components/modals/CustomModal.jsx
  src/config/demoGuideConfig.js
  src/scss/partials/_index.scss
  src/scss/partials/_modals.scss
  src/utils/ErrorHandler.jsx
Labels: Feature

#291 Feature/lighthouse seo
  .eslintrc.cjs
  index.html
  public/index.html
  public/robots.txt
  src/components/header/components/Navigation.jsx
Labels: Improvement

#293 Update readme
  README.md
Labels: Documentation

#299 infinite scroll done
  src/components/hits/Hits.jsx
  src/components/hits/components/CustomHits.jsx
  src/components/hits/components/InfluencerCard.jsx
  src/components/hits/components/NoCtaCard.jsx
  src/components/hits/components/SalesCard.jsx
  src/components/hits/components/injected-hits/InjectedHits.jsx
  src/components/searchresultpage/srpLaptop/SrpLaptop.jsx
  src/scss/partials/_mixin.scss
Labels: Feature, S
